import type { Metadata } from "next";
import Link from "next/link";
import { Download, Linkedin, Mail, MessageCircle } from "lucide-react";
import { siteUrl } from "@/lib/site";
import SocialMediaProof from "@/components/SocialMediaProof";

export const metadata: Metadata = {
    title: "Community Manager & Content Creator",
    description: "CV et réalisations de Joro Sullivan Rakotoniaina, Community Manager & Content Creator basé à Antananarivo.",
    alternates: { canonical: `${siteUrl}/recrutement` },
};

export default function RecrutementPage() {
    return <main id="main-content" className="relative">
        <section className="noise relative overflow-hidden bg-background-dark px-4 pb-16 pt-28 text-[#f8f9fa] sm:px-6 md:pb-24"><div className="container-custom relative z-10 mx-auto max-w-5xl"><Link href="/" className="text-sm font-semibold text-accent-gold hover:text-white focus:outline-none focus-visible:ring-2 focus-visible:ring-accent-gold">← Retour au portfolio</Link><p className="mt-12 text-sm font-semibold uppercase tracking-[0.18em] text-primary-violet-light">Dossier de candidature</p><h1 className="mt-4 max-w-4xl text-4xl font-bold leading-tight sm:text-5xl md:text-6xl">Community Manager &amp; Content Creator</h1><p className="mt-6 max-w-3xl text-lg leading-relaxed text-[#f8f9fa]/80">J’aide les marques à renforcer leur visibilité avec une stratégie éditoriale structurée, des contenus engageants et un suivi régulier des performances.</p><p className="mt-5 text-sm font-semibold text-primary-violet-light">Disponible pour un CDI, une mission freelance ou un temps partiel à distance. Basé à Antananarivo.</p><div className="mt-9 flex flex-wrap gap-4"><a href="/CV_Joro%20Sullivan_RAKOTONIAINA.pdf" download className="inline-flex items-center gap-2 rounded-full bg-highlight px-6 py-3 font-semibold text-white focus:outline-none focus-visible:ring-2 focus-visible:ring-accent-gold"><Download size={18} aria-hidden="true" />Télécharger mon CV</a><a href="mailto:jorosullivan13@gmail.com" className="inline-flex items-center gap-2 rounded-full border border-white/35 px-6 py-3 font-semibold text-white focus:outline-none focus-visible:ring-2 focus-visible:ring-accent-gold"><Mail size={18} aria-hidden="true" />Me contacter</a></div></div></section>
        <section className="section-padding relative" style={{ zIndex: 5 }}><div className="container-custom grid gap-10 lg:grid-cols-2"><div><span className="text-sm font-medium uppercase tracking-wider text-highlight">Compétences</span><h2 className="mt-4 text-3xl font-bold">Ce que je maîtrise</h2><p className="mt-5 leading-relaxed text-muted-foreground">Stratégie éditoriale, création de contenus statiques et vidéo, Reels, captions, planification, modération et analyse de performance.</p></div><div><span className="text-sm font-medium uppercase tracking-wider text-highlight">Outils</span><div className="mt-5 flex flex-wrap gap-3">{["Canva", "CapCut", "Meta Business Suite", "Facebook", "Reels", "Google Workspace"].map((tool) => <span key={tool} className="rounded-full border border-highlight/20 bg-highlight/10 px-4 py-2 text-sm font-semibold text-highlight">{tool}</span>)}</div><p className="mt-8 text-sm leading-relaxed text-muted-foreground">Langues : malgache (maternelle), français (professionnel), anglais (intermédiaire).</p></div></div></section>
        <SocialMediaProof />
        <section className="section-padding relative bg-muted/30" style={{ zIndex: 5 }}><div className="container-custom text-center"><h2 className="text-3xl font-bold">Restons en contact</h2><div className="mt-7 flex flex-wrap justify-center gap-5"><a href="mailto:jorosullivan13@gmail.com" className="inline-flex items-center gap-2 font-semibold text-highlight"><Mail size={18} />Email</a><a href="https://www.linkedin.com/in/sullivan-rakotoniaina/" target="_blank" rel="noopener noreferrer" className="inline-flex items-center gap-2 font-semibold text-highlight"><Linkedin size={18} />LinkedIn</a><a href="https://wa.me/261341060802" target="_blank" rel="noopener noreferrer" className="inline-flex items-center gap-2 font-semibold text-highlight"><MessageCircle size={18} />WhatsApp</a></div></div></section>
    </main>;
}