import { BarChart3, CalendarDays, MessageCircle, PenTool, Search, Share2 } from "lucide-react";

const process = [
    { icon: Search, title: "Comprendre", text: "Contexte, moyens, audience et vraie priorite." },
    { icon: PenTool, title: "Clarifier", text: "Angle, message, ton de voix et prochaine action." },
    { icon: CalendarDays, title: "Structurer", text: "Rythme, calendrier, formats et validations." },
    { icon: Share2, title: "Construire", text: "Creation, publication, coordination et suivi." },
    { icon: BarChart3, title: "Apprendre", text: "Indicateurs, contenus utiles et pistes d'amelioration." },
    { icon: MessageCircle, title: "Recommencer", text: "Retours simples pour ajuster sans perdre la direction." },
];

export default function SocialMediaProof() {
    return <>
        <section id="case-studies" className="section-padding relative bg-muted/30" style={{ zIndex: 5 }}>
            <div className="container-custom"><div className="grid gap-10 lg:grid-cols-[0.8fr_1.2fr] lg:items-start">
                <div><span className="text-sm font-medium uppercase tracking-wider text-highlight">Preuve concrète</span><h2 className="mt-4 text-3xl font-bold leading-tight sm:text-4xl">Groupe Passion Prestige - adapter le contenu à plusieurs réalités de marque</h2><p className="mt-5 text-lg leading-relaxed text-muted-foreground">Depuis mai 2026, j’accompagne un groupe multi-enseignes dans la stratégie éditoriale, la création, la programmation et l’analyse de contenus pour la beauté, le bien-être, la coiffure et l’univers premium.</p></div>
                <dl className="grid gap-4 sm:grid-cols-2">
                    <div className="glass-card rounded-2xl p-5"><dt className="text-sm font-semibold text-highlight">Enseignes</dt><dd className="mt-2 text-muted-foreground">Amazones, Majorel, Imperial Beauty &amp; Spa, Tchip Coiffure Madagascar et Passion Beaute Madagascar.</dd></div>
                    <div className="glass-card rounded-2xl p-5"><dt className="text-sm font-semibold text-highlight">Role</dt><dd className="mt-2 text-muted-foreground">Assistant Marketing et Community Manager.</dd></div>
                    <div className="glass-card rounded-2xl p-5"><dt className="text-sm font-semibold text-highlight">Comprendre</dt><dd className="mt-2 text-muted-foreground">Identifier les differences entre les marques, leurs publics, leurs offres et leurs contraintes.</dd></div>
                    <div className="glass-card rounded-2xl p-5"><dt className="text-sm font-semibold text-highlight">Adapter</dt><dd className="mt-2 text-muted-foreground">Transformer une direction commune en contenus coherents pour chaque univers.</dd></div>
                    <div className="glass-card rounded-2xl p-5"><dt className="text-sm font-semibold text-highlight">Construire</dt><dd className="mt-2 text-muted-foreground">Visuels, publications, carrousels, videos courtes, Reels, captions et programmation.</dd></div>
                    <div className="glass-card rounded-2xl p-5"><dt className="text-sm font-semibold text-highlight">Apprendre</dt><dd className="mt-2 text-muted-foreground">Suivi des indicateurs, identification des contenus performants et recommandations.</dd></div>
                </dl>
            </div><div className="mt-12"><div className="mb-5 flex flex-col gap-2 sm:flex-row sm:items-end sm:justify-between"><div><span className="text-sm font-semibold uppercase tracking-wider text-highlight">Resultats observes</span><h3 className="mt-2 text-2xl font-bold">Performances consolidees sur 28 jours</h3></div><p className="max-w-md text-sm text-muted-foreground">Donnees issues de plusieurs comptes geres au sein du groupe.</p></div><dl className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4">
                <div className="glass-card rounded-2xl border-highlight/30 p-5"><dt className="text-3xl font-bold text-highlight">101,9 K</dt><dd className="mt-2 text-sm text-muted-foreground">vues sur Facebook</dd></div>
                <div className="glass-card rounded-2xl border-highlight/30 p-5"><dt className="text-3xl font-bold text-highlight">+74,7 %</dt><dd className="mt-2 text-sm text-muted-foreground">de croissance des vues</dd></div>
                <div className="glass-card rounded-2xl border-highlight/30 p-5"><dt className="text-3xl font-bold text-highlight">3,3 K</dt><dd className="mt-2 text-sm text-muted-foreground">interactions</dd></div>
                <div className="glass-card rounded-2xl border-highlight/30 p-5"><dt className="text-3xl font-bold text-highlight">+23,4 %</dt><dd className="mt-2 text-sm text-muted-foreground">de croissance des interactions</dd></div>
                <div className="glass-card rounded-2xl p-5"><dt className="text-2xl font-bold text-highlight">+555 %</dt><dd className="mt-2 text-sm text-muted-foreground">de progression des vues Instagram</dd></div>
                <div className="glass-card rounded-2xl p-5"><dt className="text-2xl font-bold text-highlight">+376 %</dt><dd className="mt-2 text-sm text-muted-foreground">de progression de la portee Instagram</dd></div>
                <div className="glass-card rounded-2xl p-5"><dt className="text-2xl font-bold text-highlight">42</dt><dd className="mt-2 text-sm text-muted-foreground">contacts generes via la messagerie</dd></div>
                <div className="glass-card rounded-2xl p-5"><dt className="text-2xl font-bold text-highlight">72</dt><dd className="mt-2 text-sm text-muted-foreground">nouveaux abonnements</dd></div>
            </dl><div className="mt-4 grid gap-4 md:grid-cols-2"><div className="glass-card rounded-2xl p-5"><h4 className="font-semibold text-highlight">Développement de l’audience</h4><p className="mt-2 text-sm leading-relaxed text-muted-foreground">54,7 K spectateurs Facebook (+95,6 %), 79 076 vues provenant de non-abonnés et 13 181 vues Instagram provenant de non-abonnés.</p></div><div className="glass-card rounded-2xl p-5"><h4 className="font-semibold text-highlight">Contenu sponsorisé</h4><p className="mt-2 text-sm leading-relaxed text-muted-foreground">14 716 vues, 46 interactions, 4 nouveaux abonnements, 1 047 ThruPlays et 11 958 vues générées via la promotion pour 0,96 $ de budget média utilisé.</p></div></div></div><p className="mt-8 rounded-xl border border-accent-gold/30 bg-accent-gold/10 p-4 text-sm leading-relaxed text-foreground">Les résultats présentés sont des données consolidées issues de plusieurs comptes du Groupe Passion Prestige. Les statistiques peuvent varier selon les enseignes, les périodes et les campagnes.</p></div>
        </section>
        <section className="section-padding relative" style={{ zIndex: 5 }}><div className="container-custom"><div className="mx-auto max-w-3xl text-center"><span className="text-sm font-medium uppercase tracking-wider text-highlight">Méthode</span><h2 className="mt-4 text-3xl font-bold sm:text-4xl">Un chemin simple quand tout n’est pas encore clair</h2><p className="mt-5 text-lg leading-relaxed text-muted-foreground">La méthode reste volontairement lisible : comprendre, clarifier, construire, regarder ce que ça donne, puis ajuster.</p></div><ol className="mt-12 grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{process.map((step, index) => <li key={step.title} className="glass-card flex gap-4 rounded-2xl p-5"><div className="flex h-11 w-11 shrink-0 items-center justify-center rounded-xl bg-highlight/10 text-highlight"><step.icon size={21} aria-hidden="true" /></div><div><span className="text-xs font-bold text-highlight">0{index + 1}</span><h3 className="font-semibold">{step.title}</h3><p className="mt-1 text-sm text-muted-foreground">{step.text}</p></div></li>)}</ol></div></section>
    </>;
}
